// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20221226142024_CreateTable")]
    partial class CreateTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BarCode")
                        .HasColumnType("varchar")
                        .HasColumnName("bar_code");

                    b.Property<string>("Brands")
                        .HasColumnType("varchar")
                        .HasColumnName("brands");

                    b.Property<string>("Categories")
                        .HasColumnType("varchar")
                        .HasColumnName("categories");

                    b.Property<long?>("Code")
                        .HasColumnType("int8")
                        .HasColumnName("code");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("varchar")
                        .HasColumnName("image-url");

                    b.Property<DateTime>("Imported_at")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("Packaging")
                        .HasColumnType("varchar")
                        .HasColumnName("packaging");

                    b.Property<string>("ProductName")
                        .HasColumnType("varchar")
                        .HasColumnName("product_name");

                    b.Property<string>("Quantity")
                        .HasColumnType("varchar")
                        .HasColumnName("quantity");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("Url")
                        .HasColumnType("varchar")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
